default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Hogehogemaster.0904
  host: localhost


development:
  <<: *default
  database: fishpod_development #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

test:
  <<: *default
  database: fishpod_test #　DBの名前。「sample」の部分をアプリの名前に変更すると分かりやい

production:
  <<: *default
  database: fishpod_production
  username: fishpod_app
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>